name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  repository_dispatch:
  # 手动触发工作流
  workflow_dispatch:
    inputs:
      build:
        description: 'Deploy to Cloudflare Workers'
        required: true
        default: 'Deploy to Cloudflare Workers'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        env:
          CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN || 'xiaonuo.in' }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{secrets.CF_ACCOUNT_ID}}
          vars:
            CUSTOM_DOMAIN
          command: deploy --env production --minify src/index.js
          environment: production
